landingpage/urls.py
from django.urls import path
from .views import index, add_status, about

app_name = 'landingpage'

urlpatterns = [
    path('status/', index, name = 'index'),
    path('add_status/', add_status, name='add_status'),
    path('about/', about, name = 'about'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('books/', include('story8.urls')),
    path('', include('story9.urls')),
]

story8/urls.py
from django.urls import path
from .views import books

app_name = 'story8'

urlpatterns = [
    path('', books, name = 'books'),
]

story9/urls.py
from django.urls import path
from .views import index, loginView, logoutView

app_name = 'story9'

urlpatterns = [
    path('', index, name = 'index'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
]

landingpage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	status = models.TextField(blank=False, max_length=300)
	status_time = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ('-status_time',)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

landingpage/forms.py
from django import forms
from django.forms import Form

class Status_Form(forms.Form):
	pos_attrs = {
		'type': 'text',
		'class':'form-control',
		'placeholder':'Write your status here'
	}

	status = forms.CharField(required=True, widget=forms.Textarea(attrs=pos_attrs), max_length=300)

landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
def index(request):
	response = {"status_form": Status_Form}
	statuses = Status.objects.all().values()
	response['status'] = statuses
	return render(request, 'index.html', response)

def add_status(request):
	if(request.method == 'POST'):
		form = Status_Form(request.POST)
		if (form.is_valid()):
			status_fill = form.cleaned_data['status']
			status = Status(status = status_fill)
			status.save()
	
		return HttpResponseRedirect('/status/')

def about(request):
	return render(request, 'about.html')

story8/views.py
from django.shortcuts import render

def books(request):
	return render (request, "books.html")

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):

	template_name = None

	if request.user.is_authenticated:
		#untuk user
		template_name = 'welcome.html'

	else:
		#untuk anon
		template_name = 'welcome-login.html'

	host = request.get_host()
	port = request.get_port()

	context = {
        'host':host,
        'port':port,
    }

	return render(request, template_name, context)

def loginView(request):

	user = None

	if request.method == "POST":
		username_login = request.POST['username']
		password_login = request.POST['password']

		user = authenticate(request, username=username_login, password=password_login)

		if user is not None:
			login(request, user)
			return redirect('story9:index')
		else:
			return redirect('story9:login')
	return render(request, 'login.html')
		
# @login_required
def logoutView(request):

	if request.method == "POST":
		if request.POST['logout'] == "Yes":
			logout(request)
		

		return redirect('story9:index')
	return render(request, 'logout.html')

landingpage/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}

<div id="title">About Me</div>

<div class="wrapper">
	<ul class="accordion child">
		<li class='acc-list'>
			<a class="panels" href="#">Activities</a>
			<ul class="content">
				<p>Eat</p>
			    <p>Sleep</p>
			    <p>Watching movies</p>
			</ul>
		</li>

		<li class='acc-list'>
			<a class="panels" href="#">Experiences</a>
			<ul class="content">
				<p>Staff of Entrepreneurial Division - DPM Fasilkom UI 2019</p>
				<p>Staff of Public Relations - SIWAK-NG 2019</p>
				<p>Staff of Public Relations - Wisuda Genap Fasilkom UI 2019</p>
			</ul>
		</li>

		<li class='acc-list'>
			<a class="panels" href="#">Achievements</a>
			<ul class="content">
			    <p>Soon</p>
			</ul>
		</li>
    </ul>
</div>

{% endblock %}

landingpage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <title>{% block title %}{% endblock title %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="#" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300i,400,700i,900i&display=swap" rel="stylesheet"> 

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script> 
    <script src="{% static 'js/bootstrap.min.js' %}"></script> 


    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <script src="{% static 'js/accordion.js' %}"></script>
    {% block custom_scripts %}
    {% endblock %}
</head>

<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top py-0">
        <a class="navbar-brand header-title" href="#">Salsabila Adnan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
             
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'story9:index' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'landingpage:index' %}">Status<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'landingpage:about' %}">About<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active header-subtitle">
                    <a class="nav-link" href="{% url 'story8:books' %}">Books<span class="sr-only">(current)</span></a>
                </li>           
            </ul>
        </div>    
    </nav>

    <br>
    <br>

    <div class="wrapper">
        <button onclick="lightMode()" id="light">Light Mode</button>
        <button onclick="darkMode()" id="dark">Dark Mode</button>
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>

landingpage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Halo{% endblock title %}

{% block content %}
	
	<div id="title">Halo, Apa Kabar?</div>

	<div class="container">
		<div class="row justify-content-center">
			<form id="form" method="POST" action="{% url 'landingpage:add_status' %}">	
				<center>
					<br>
					{% csrf_token %}
					{{ status_form.status}}
					<br>
					<button id="submit-btn" class="button" type="submit" class="btn btn-info">Add Status</button>
				</center>
			</form>
		</div>

		<hr>
		
		<div class="row">
			{% if status %}
				{% for data in status %}
				<div class="col-sm-3">
					<div id="card" class="card mb-3">
					    <div class="card-body">{{ data.status }}</div> 
					    <footer class="blockquote-fo boter"><cite title="Source Title">{{ data.status_time }}</cite></footer>
					</div>
				</div>
				{% endfor %}
	        {% endif %}
		</div>
	</div>
{% endblock %}

story8/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block custom_scripts %}
    <script src="{% static 'js/search_book.js' %}"></script>
{% endblock %}

{% block title %}Books{% endblock title %}

{% block content %}
	
	<div id="title">Books Search</div>

	<div class="container">

	    <div class="row">
            <div class="col">	
            	<input type="text" class="form-control" id="searchbook" placeholder="Type the title or author">
		    </div>
	    </div>
    
		<div class="row">
            <div class="col">
                <table class="table table-hover" id="table2">
                </table>
            </div>
        </div>	
	</div>
{% endblock %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
	
	<div id="title">Login</div>

	<div class="container">
	    
		<form id = "input-form" method="POST">
			<center>
				{% csrf_token %}

				<label for="username">Username: </label>
		        <input  type="text" name="username" id="username">
		        <br>
		        <label for="password">Password: </label>
		        <input type="password" name="password" id="password">
		        <br>

		        <button class="btn btn-dark " type="submit" id="submit-but">Login</button>
			</center>    
		</form>

	</div>


	</div>

{% endblock %}

story9/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Logout{% endblock title %}

{% block content %}
	
	<div id="title">Logout</div>

	<div class="container">
		<center>
			<h1> Are you sure want to logout, {{user}}?</h1>
			
			<form  method="POST">
				{% csrf_token %}

			    <input class="btn btn-dark btn-block " value="Yes" type="submit" name="logout" id="logout-yes">

			    <input class="btn btn-dark btn-block " value="No" type="submit" name="logout">
			    
			</form>
		</center>
		
	</div>

	</div>

{% endblock %}

story9/templates/welcome-login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome{% endblock title %}

{% block content %}
	
	<div id="title">Welcome</div>

	<div class="container">
		<center>
			<h3>
		        This website is served by:  <br>
		        HOST: {{ host }}            <br>
		        PORT: {{ port }}            
	    	</h3>
	    	<br>
		</center>

		<a class="btn btn-dark btn-block " href="{% url 'story9:login' %}" id="login-but">Login</a>		
{% endblock %}

story9/templates/welcome.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome{% endblock title %}

{% block content %}
	
	<div id="title">Welcome {{user}}</div>

	<div class="container">
		<center>
			<h3>
		        This website is served by:  <br>
		        HOST: {{ host }}            <br>
		        PORT: {{ port }}            
	    	</h3>
			<br>	    	
		</center>

		<a class="btn btn-dark btn-block " href="{% url 'story9:logout' %}" id="logout-but">Logout</a>
	</div>

{% endblock %}